
version: "3"
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booklet_byseven_co_development
    networks:
      - seven_booklet
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  seven_booklet:
    driver: bridge

volumes:
  postgres:
    driver: local


